services:
     client:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: con-client
        networks:
            - exam-net
        ports:
            - 8080:5000
        depends_on:
            - storage
     storage:
        build:
            context: ./storage
            dockerfile: Dockerfile
        container_name: con-storage
        networks:
            - exam-net
        environment:
            MYSQL_ROOT_PASSWORD: "ExamPa$$w0rd"
        depends_on:
            - generator
     generator:
        build:
            context: ./generator
            dockerfile: Dockerfile
        container_name: con-generator
        networks:
            - exam-net
networks:
    exam-net:
        external: true
        name: exam-net