{
 "title": "Exam-Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Time Spent Total",
   "type": "timeseries",
   "description": "Total time spent generating Fun Facts",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    { "expr": "time_spent_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Partition Offset",
   "type": "timeseries",
   "description": "Kafka Topic Partition Current Offset",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Facts Total",
   "type": "timeseries",
   "description": "Total Fun Facts discovered by the Discoverer",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 8 },
   "targets": [
    { "expr": "discovered_facts_total", "legendFormat": "__auto" }
   ]
  }
 ]
}