pipeline
{
    agent any

    stages
    {
        stage('Clone the project')
        {
            steps
            {
                sh '''
                cd /projects
                if [ -d /projects/demo-app ]; then
                  cd /projects/demo-app
                  git pull https://github.com/ilkothetiger/demo-app.git
                else
                  git clone https://github.com/ilkothetiger/demo-app.git
                fi
                '''
            }
        }

        stage('Create a network')
        {
            steps
            {
                sh '''
                docker network rm appnet || true
                docker network ls | grep appnet || docker network create appnet
                '''
            }
        }

        stage('Build the Web Image')
        {
            steps
            {
                sh 'cd /projects/demo-app && docker image build -t img-web -f Dockerfile.web .'
            }
        }
        
        stage('Run the Web app')
        {
            steps
            {
                sh '''
                docker container rm -f web || true
                docker container run -d --name web --net appnet -p 9090:80 -v /projects/demo-app/web:/var/www/html:ro img-web
                '''
            }
        }

                stage('Build the DB Image')
        {
            steps
            {
                sh 'cd /projects/demo-app && docker image build -t img-db -f Dockerfile.db .'
            }
        }

                stage('Run the Database')
        {
            steps
            {
                sh '''
                docker container rm -f db || true
                docker container run -d --name db --net appnet -e MYSQL_ROOT_PASSWORD=12345 img-db
                '''
            }
        }
    }
}