# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   config.ssh.insert_key = false

   config.vm.define "docker" do |docker|
     config.vm.box = "shekeriev/centos-stream-8"
     docker.vm.hostname = "docker"
     docker.vm.network "private_network", ip: "192.168.99.100"

     docker.vm.provision "shell", inline: <<EOS
echo " Adding EPEL repository ..."
dnf install -y epel release

echo " Installing Python3 ..."
dmf install -y python3 python3-pip

echo " Installing Python Docker module ..."
pip install docker
EOS
   end
end
