# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.box = "shekeriev/centos-stream-8"

  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.memory = 2048
    v.cpus = 1
  end

  # Docker Machine - CentOS Stream 9
  config.vm.define "docker" do |docker|
    docker.vm.hostname = "docker"
    docker.vm.network "private_network", ip: "192.168.99.100"
    docker.vm.provision "shell", path: "add_hosts.sh"
  end

end
