# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "ans" do |ans|
    ans.vm.box = "shekeriev/centos-stream-9"
    ans.vm.hostname = "ans.do2.lab"
    ans.vm.network "private_network", ip: "192.168.99.99"
    ans.vm.provision "shell", inline: <<EOS
dnf install -y ansible-core
ansible-galaxy collection install -p /usr/share/ansible/collections ansible.posix
EOS
  end

  config.vm.define "web" do |web|
    web.vm.box = "shekeriev/centos-stream-9"
    web.vm.hostname = "web.do2.lab"
    web.vm.network "private_network", ip: "192.168.99.100"
    web.vm.network "forwarded_port", guest: 80, host: 8080
  end
end