---
- hosts: all
  roles:
    - geerlingguy.docker
  
  tasks:
    - name: Add vagrant user to docker group
      user:
        name: 'vagrant'
        group: docker
        append: yes

    - name: Create a network
      docker_network:
        name: exam-net