pipeline
{
    agent
    {
        label 'docker-node'
    }
    environment
    {
        DOCKERHUB_CREDENTIALS=credentials('docker-hub')
    }
    stages
    {
        stage('Clone')
        {
            steps
            {
                git branch: 'main', url: 'http://192.168.99.102:3000/exam/exam'
            }  
        }
        stage('Create a network')
        {
            steps
            {
                sh '''
                docker network rm app-net || true
                docker network ls | grep app-net || docker network create app-net
                '''
            }
        }
        stage('Build the Images')
        {
            steps
            {
                sh 'docker image rm -f pipeline-dob-producer pipeline-dob-storage pipeline-dob-consumer || true'
                sh 'docker compose -f docker-compose-run.yml build'
            }
        }
        stage('Run the Containers')
        {
            steps
            {
                sh 'docker container rm -f dob-producer dob-storage dob-consumer || true'
                sh 'docker container rm -f pipeline-exam-producer-1 pipeline-exam-storage-1 pipeline-exam-consumer-1  || true'
                sh 'docker compose -f docker-compose-run.yml up -d'
            }
        }
        stage('CleanUp')
        {
            steps
            {
                sh 'docker container rm -f pipeline-exam-producer-1 pipeline-exam-storage-1 pipeline-exam-consumer-1 || true'
            }
        }
        stage('Login')
        {
            steps
            {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Push')
        {
            steps
            {
                sh 'docker image rm ilkothetiger/exam-producer ilkothetiger/exam-storage ilkothetiger/exam-consumer || true'
                sh 'docker image tag docker-producer ilkothetiger/exam-producer'
                sh 'docker image tag docker-storage ilkothetiger/exam-storage'
                sh 'docker image tag docker-consumer ilkothetiger/exam-consumer'
                sh 'docker push ilkothetiger/exam-producer'
                sh 'docker push ilkothetiger/exam-storage'
                sh 'docker push ilkothetiger/exam-consumer'
            }
        }
        stage('Deploy')
        {
            steps
            {
                sh 'docker image rm -f docker-producer-1 docker-storage-1 docker-consumer-1 || true'
                sh 'docker compose -f docker-compose-deploy.yml up -d'
            }
        }
    }
}