# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box="shekeriev/centos-stream-9"
    jenkins.vm.hostname = "pipelines.do1.exam"
    jenkins.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "3072"]
    end
    jenkins.vm.network "private_network", ip: "192.168.99.201"
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080
    jenkins.vm.provision "shell", path: "add_hosts.sh"
	  jenkins.vm.provision "shell", path: "install_jenkins.sh"
  end
  
  config.vm.define "containers" do |containers|
    containers.vm.box = "shekeriev/centos-stream-9"
    containers.vm.hostname = "containers.do1.exam"
    containers.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "3072"]
    end
    containers.vm.network "private_network", ip: "192.168.99.202"
    containers.vm.network "forwarded_port", guest: 8080, host: 8081
    containers.vm.provision "shell", path: "add_hosts.sh"
	  containers.vm.provision "shell", path: "install_docker.sh"
    containers.vm.provision "shell", path: "setup_gitea.sh"
  end
  
  config.vm.define "monitor" do |monitor|
    monitor.vm.box = "shekeriev/centos-stream-9"
    monitor.vm.hostname = "monitoring.do1.exam"
    monitor.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "3072"]
    end
    monitor.vm.network "private_network", ip: "192.168.99.203"
    monitor.vm.network "forwarded_port", guest: 3000, host: 8082
    monitor.vm.provision "shell", path: "add_hosts.sh"
    monitor.vm.provision "shell", path: "install_docker_monitoring.sh"
  end

end
