{
 "title": "HW6",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "This is metrics coming from node_exportrs on Jenkins and Cocker machines",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance)(node_memory_Percpu_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "description": "This is data coming from node_exports on Jenkins and Docker machines",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance)(node_memory_MemFree_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Count of Containers in All States",
   "type": "stat",
   "description": "This is metrics for Docker containers in all states coming from node_exporters jenkins and containers machine",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers"
    }
   ]
  }
 ]
}