# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define "server" do |server|
    server.vm.box = "shekeriev/centos-stream-9"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.99.101"
    server.vm.provision "shell", path: "add-hosts.sh"
    server.vm.provision "shell", path: "elastic-stack.sh"

    server.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 4096
      v.cpus = 2
      v.cpus = 1
    end
  end
  
  config.vm.define "node1" do |node1|
    node1.vm.box = "shekeriev/centos-stream-9"
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", ip: "192.168.99.102"
    node1.vm.provision "shell", path: "add-hosts.sh"
    node1.vm.provision "shell", path: "metricbeat-centos.sh"

    node1.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end
  end
  
  config.vm.define "node2" do |node2|
    node2.vm.box = "ubuntu/trusty64"
    node2.vm.hostname = "node2"
    node2.vm.network "private_network", ip: "192.168.99.103"
    node2.vm.provision "shell", path: "add-hosts.sh"
    node2.vm.provision "shell", path: "metricbeat-ubuntu.sh"

    node2.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end
  end
end
