{
 "title": "Exam-Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Kafka Brokers",
   "type": "timeseries",
   "description": "Count of Brokers",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    { "expr": "kafka_brokers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Partition Offset",
   "type": "timeseries",
   "description": "Kafka Topic Partition Current Offset",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Topic Partitions",
   "type": "timeseries",
   "description": "Count of Topics",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 8 },
   "targets": [
    { "expr": "kafka_topic_partitions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Oldest Offset",
   "type": "timeseries",
   "description": "Kafka Topic Partition Oldest Offset",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "kafka_topic_partition_oldest_offset",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}