# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  $puppet = <<PUPPET
    sudo dnf install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
    sudo dnf install -y puppet
PUPPET

  $modulesnginx = <<MODULESNGINX
    puppet module install puppetlabs-firewall
    puppet module install puppetlabs-docker --version 7.0.0
    sudo cp -vR ~/.puppetlabs/etc/code/modules/ /etc/puppetlabs/code/
MODULESNGINX

  # NGINX - CentOS Stream 8
  config.vm.define "client1" do |client1|
    client1.vm.box = "shekeriev/centos-stream-8"
    client1.vm.hostname = "nginx"
    client1.vm.network "private_network", ip: "192.168.99.101"
    client1.vm.provision "shell", path: "add_hosts.sh"
    client1.vm.provision "shell", inline: $puppet, privileged: false
    client1.vm.provision "shell", inline: $modulesnginx, privileged: false

    client1.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "nginx.pp"
      puppet.options = "--verbose --debug"
    end

    client1.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end
  end
  
end
