# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  
  # Chef Workstation - CentOS Stream 9
  config.vm.define "workstation" do |workstation|
    workstation.vm.box = "shekeriev/centos-stream-9"
    workstation.vm.hostname = "chef-wrkstn"
    workstation.vm.network "private_network", ip: "192.168.99.101"
    workstation.vm.provision "shell", path: "add_hosts.sh"
    workstation.vm.provision "shell", path: "install_workstation.sh"

    workstation.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 1
    end
  end
  
end
