# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false
  
  config.vm.define "vagrant" do |vagrant|
    vagrant.vm.box="shekeriev/centos-stream-9"
    vagrant.vm.hostname = "host.do1.lab"
    vagrant.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
    end
    vagrant.vm.network "private_network", ip: "192.168.99.101"
    vagrant.vm.provision "shell", path: "add_hosts.sh"
    vagrant.vm.provision "shell", path: "install_docker_centos.sh"
    vagrant.vm.provision "shell", path: "goprom.sh"
    vagrant.vm.provision "shell", path: "install_prometheus.sh"
  end

end
