{
 "title": "Kafka Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Kafka Metrics",
   "type": "timeseries",
   "description": "Metrics delivered by Kafka Exporter",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cycles Total",
   "type": "timeseries",
   "description": "Count of completed GC cycles generated by the Go runtime.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "go_gc_cycles_automatic_gc_cycles_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processes Open",
   "type": "gauge",
   "description": "Number of open file descriptors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Topic Partitions",
   "type": "stat",
   "description": "Count of Kafka Topic Partitions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_topic_partitions", "legendFormat": "__auto" }
   ]
  }
 ]
}