global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['192.168.99.100:9101']
      - targets: ['192.168.99.100:9102']
      - targets: ['192.168.99.100:9103']