---
- hosts: webserver
  become: true

  tasks:
    - name: Install Apache HTTP Server
      dnf: name=httpd state=present

    - name: Start Apache HTTP Server and Enable it
      service: name=httpd state=started enabled=true

    - name: Copy web folder
      copy: src=web dest=/var/www/html/

    - name: Allow HTTP service in the firewall
      firewalld: service=http state=enabled permanent=yes immediate=yes