# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "server" do |server|
    server.vm.box = "shekeriev/centos-stream-9"
    server.vm.hostname = "server.do2.lab"
    server.vm.network "private_network", ip: "192.168.99.99"
    server.vm.provision "shell", path: "add_hosts.sh"
    server.vm.provision "shell", path: "provision.sh"
  end

  config.vm.define "web" do |web|
    web.vm.box = "shekeriev/centos-stream-9"
    web.vm.hostname = "web.do2.lab"
    web.vm.network "private_network", ip: "192.168.99.100"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.provision "shell", path: "add_hosts.sh"
    web.vm.provision "shell", path: "minion_provision.sh"
  end
end