---
- hosts: dbserver
  become: true

  tasks:

  - name: Install Utility software
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - software-properties-common
      - mariadb-server

  - name: “Copy Files”
    copy:
       dest: /home/vagrant/db/
       src: db/
       directory_mode: true
    notify: “db_restart”

  - name: Open external ports
    shell: sed -i.bak s/127.0.0.1/0.0.0.0/g /etc/mysql/mariadb.conf.d/50-server.cnf

  - name: Create and Load Database
    shell: mysql -u root < /home/vagrant/db/db_setup.sql || true

  handlers:
  - name: “db_restart”
    service:
       name: mariadb
       state: restarted