global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['192.168.99.100:8081']
      - targets: ['192.168.99.100:8082']
      - targets: ['192.168.99.100:8083']