pipeline
{
    agent
    {
        label 'docker-node'
    }
    environment
    {
        DOCKERHUB_CREDENTIALS=credentials('docker-hub')
    }
    stages
    {
        stage('Clone')
        {
            steps
            {
                git branch: 'main', url: 'http://192.168.99.101:3000/ilia/exam'
            }  
        }
        stage('Create a network')
        {
            steps
            {
                sh '''
                sudo docker network rm appnet pipeline-exam_appnet deploy_appnet || true
                sudo docker network ls | grep appnet || sudo docker network create appnet
                '''
            }
        }
        stage('Build the Images')
        {
            steps
            {
                sh 'sudo docker image rm -f pipeline-exam-producer pipeline-exam-storage pipeline-exam-consumer || true'
                sh 'sudo docker compose build'
            }
        }
        stage('Run the Containers')
        {
            steps
            {
                sh 'sudo docker container rm -f dob-producer dob-storage dob-consumer || true'
                sh 'sudo docker container rm -f pipeline-exam-producer-1 pipeline-exam-storage-1 pipeline-exam-consumer-1  || true'
                sh 'sudo docker compose up -d'
            }
        }
        stage('CleanUp')
        {
            steps
            {
                sh 'sudo docker container rm -f pipeline-exam-producer pipeline-exam-storage pipeline-exam-consumer || true'
            }
        }
        stage('Login')
        {
            steps
            {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | sudo docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Push')
        {
            steps
            {
                sh 'sudo docker image rm ilkothetiger/exam-producer ilkothetiger/exam-storage ilkothetiger/exam-consumer || true'
                sh 'sudo docker image tag pipeline-exam-producer ilkothetiger/exam-producer'
                sh 'sudo docker image tag pipeline-exam-storage ilkothetiger/exam-storage'
                sh 'sudo docker image tag pipeline-exam-consumer ilkothetiger/exam-consumer'
                sh 'sudo docker push ilkothetiger/exam-producer'
                sh 'sudo docker push ilkothetiger/exam-storage'
                sh 'sudo docker push ilkothetiger/exam-consumer'
            }
        }
        stage('Deploy')
        {
            steps
            {
                sh 'sudo docker image rm -f pipeline-exam-producer-1 pipeline-exam-storage-1 pipeline-exam-consumer-1 || true'
                sh 'cd deploy && sudo docker compose up -d'
            }
        }
    }
}