# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box="shekeriev/centos-stream-9"
    jenkins.vm.hostname = "vm100.do1.exam"
    jenkins.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "3072"]
    end
    jenkins.vm.network "private_network", ip: "192.168.99.100"
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080
    jenkins.vm.provision "shell", path: "add_hosts.sh"
	  jenkins.vm.provision "shell", path: "install_jenkins.sh"
	  jenkins.vm.provision "shell", path: "metricbeat-centos.sh"
  end
  
  config.vm.define "docker" do |docker|
    docker.vm.box = "shekeriev/centos-stream-9"
    docker.vm.hostname = "vm101.do1.exam"
    docker.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "3072"]
    end
    docker.vm.network "private_network", ip: "192.168.99.101"
    docker.vm.provision "shell", path: "add_hosts.sh"
	  docker.vm.provision "shell", path: "install_docker.sh"
	  docker.vm.provision "shell", path: "metricbeat-centos.sh"
  end

  config.vm.define "monitor" do |monitor|
    monitor.vm.box = "shekeriev/centos-stream-9"
    monitor.vm.hostname = "vm102.do1.exam"
    monitor.vm.network "private_network", ip: "192.168.99.102"
    monitor.vm.provision "shell", path: "add_hosts.sh"
    monitor.vm.provision "shell", path: "elastic-stack.sh"

    monitor.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 4096
      v.cpus = 2
      v.cpus = 1
    end
  end
end