global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
      monitor: 'exam-monitor'
scrape_configs:
  - job_name: 'jenkins'
    static_configs:
      - targets: ['192.168.99.101:9100']
  - job_name: 'docker'
    static_configs:
      - targets: ['192.168.99.102:9100']